site_name: eXpOS NITC
site_url: https://ghoshishan.github.io/
site_description: >-
  OS Lab website for NIT Calicut
  this is a multi line description

# Copyright
copyright: >-
  National Insititute of Technology, Calicut <br/>
  <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">
    <img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/80x15.png" />
  </a>

# Configuration
theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/logo.png
  theme:
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/exposnitc
    - icon: fontawesome/brands/google
      link: https://groups.google.com/g/xos-users

# Extensions
markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Page tree
nav:
  - Home: index.md
  - About Us:
    - About Us: about.md
    - Releases:
      - Changelog: changelog.md