site_name: eXpOS NITC
site_url: https://anandubajith.github.io/expos-v2/
site_description: >-
  OS Lab website for NIT Calicut
  this is a multi line description

# Copyright
copyright: >-
  National Insititute of Technology, Calicut <br/>
  <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">
    <img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/80x15.png" />
  </a>

extra_css:
  - assets/css/extra.css
repo_url: https://github.com/eXpOSNitc/eXpOSNitc.github.io
repo_name: eXpOSNitc/eXpOSNitc.github.io
# Configuration
theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/logo.png
  custom_dir: overrides
  theme:
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/exposnitc
    - icon: fontawesome/brands/google
      link: https://groups.google.com/g/xos-users

# Extensions
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Page tree
nav:
  - Home: index.md
  - Documentation:
    - Documentation: documentation.md
    - Architecture:
      - Specification: 
        - XSM Architecture Specifcation: arch-spec/index.md
        - Machine Organisation: "arch-spec/machine-org.md"
      - Modules:
        - Modules: "modules/index.md"
        - Module 0: "modules/module_00.md"
        - Module 1: "modules/module_01.md"
        - Module 2: "modules/module_02.md"
        - Module 3: "modules/module_03.md"
        - Module 4: "modules/module_04.md"
        - Module 5: "modules/module_05.md"
        - Module 6: "modules/module_06.md"
        - Module 7: "modules/module_07.md"
        - Module 8: "modules/module_08.md"
      - Tutorials:
        - MultiUser Implementation: "tutorials/multiuser_implementation.md"
        - FileSystem Implementation: "tutorials/filesystem_implementation.md"
        - Process Management Implementation: "tutorials/process_management_implementation.md"
        - XSM Instruction Cycle: "tutorials/xsm_instruction_cycle.md"
        - XSM Interrupts tutorial: "tutorials/xsm_interrupts_tutorial.md"
        - XSM Unprivileged tutorial: "tutorials/xsm_unprivileged_tutoral.md"
    - Others:
      - Test Programs:
        - Test Program 01: test_programs/test_program_01.md
        - Test Program 02: test_programs/test_program_02.md
        - Test Program 03: test_programs/test_program_03.md
        - Test Program 04: test_programs/test_program_04.md
        - Test Program 05: test_programs/test_program_05.md
        - Test Program 06: test_programs/test_program_06.md
        - Test Program 07: test_programs/test_program_07.md
        - Test Program 08: test_programs/test_program_08.md
        - Test Program 09: test_programs/test_program_09.md
        - Test Program 10: test_programs/test_program_10.md
        - Test Program 11: test_programs/test_program_11.md
        - Test Program 12: test_programs/test_program_12.md
        - Test Program 13a: test_programs/test_program_13a.md
        - Test Program 13b: test_programs/test_program_13b.md
        - Test Program 14a: test_programs/test_program_14a.md
        - Test Program 14b: test_programs/test_program_14b.md
        - Test Program 15: test_programs/test_program_15.md
        - Test Program 16a: test_programs/test_program_16a.md
        - Test Program 16b: test_programs/test_program_16b.md
        - Test Program 16c: test_programs/test_program_16c.md
        - Test Program 16d: test_programs/test_program_16d.md
  - Roadmap:
    - Roadmap: roadmap/index.md
    - Preparatory Stages:
      - Stage 1: roadmap/stage_01.md
      - Stage 2: roadmap/stage_02.md
      - Stage 3: roadmap/stage_03.md
      - Stage 4: roadmap/stage_04.md
      - Stage 5: roadmap/stage_05.md
      - Stage 6: roadmap/stage_06.md
      - Stage 7: roadmap/stage_07.md
      - Stage 8: roadmap/stage_08.md
      - Stage 9: roadmap/stage_09.md
      - Stage 10: roadmap/stage_10.md
      - Stage 11: roadmap/stage_11.md
      - Stage 12: roadmap/stage_12.md
    - Intermediate Stages:
      - Stage 13: roadmap/stage_13.md
      - Stage 14: roadmap/stage_14.md
      - Stage 15: roadmap/stage_15.md
      - Stage 16: roadmap/stage_16.md
      - Stage 17: roadmap/stage_17.md
      - Stage 18: roadmap/stage_18.md
      - Stage 19: roadmap/stage_19.md
    - Final Stages:
      - Stage 20: roadmap/stage_20.md
      - Stage 21: roadmap/stage_21.md
      - Stage 22: roadmap/stage_22.md
      - Stage 23: roadmap/stage_23.md
      - Stage 24: roadmap/stage_24.md
      - Stage 25: roadmap/stage_25.md
      - Stage 26: roadmap/stage_26.md
      - Stage 27: roadmap/stage_27.md
      - Stage 28: roadmap/stage_28.md
  - FAQ: faq.md
  - Student Feedback:
    - Student Feedback: feedback/index.md
    - NIT-C 2020: feedback/nitc20/index.md
    - NIT-C 2019: feedback/nitc19/index.md
    - IIT PKD 2018: feedback/iitpkd18/index.md
    - NIT-C 2018: feedback/nitc18/index.md
  - User Contributions: https://exposnitc.github.io/user-contrib/" target="_blank # can be moved later in this site itself
  - About:
    - About: about.md
    - Changelog: changelog.md
  - XOS: http://xosnitc.github.io" target="_blank # *hack* injected in the anchor code
