site_name: eXpOS NITC
site_url: https://anandubajith.github.io/expos-v2/
site_description: >-
  OS Lab website for NIT Calicut

# Copyright
copyright: >-
  National Insititute of Technology, Calicut <br/>
  <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">
    <img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/80x15.png" />
  </a>

extra_css:
  - assets/css/extra.css
# repo_url: https://github.com/eXpOSNitc/eXpOSNitc.github.io
# repo_name: eXpOSNitc/eXpOSNitc.github.io
# Configuration
theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/logo.png
  custom_dir: overrides
  theme:
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/exposnitc
    - icon: fontawesome/brands/google
      link: https://groups.google.com/g/xos-users

# Extensions
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Page tree
nav:
  - Home: index.md
  - Documentation:
    - Documentation: documentation.md
    - Operating System:
      - Specification: os-spec/index.md
      - Design: os-design/index.md
      - Implementation: os-implementation.md
    - Architecture:
      - Specification: 
        - XSM Architecture Specifcation: arch-spec/index.md
        - Virtual Machine Model: virtual-machine-spec.md
        - Machine Organisation: "arch-spec/machine-organization.md"
      - Modules:
        - Modules: "modules/index.md"
        - Module 0: "modules/module-00.md"
        - Module 1: "modules/module-01.md"
        - Module 2: "modules/module-02.md"
        - Module 3: "modules/module-03.md"
        - Module 4: "modules/module-04.md"
        - Module 5: "modules/module-05.md"
        - Module 6: "modules/module-06.md"
        - Module 7: "modules/module-07.md"
        - Module 8: "modules/module-08.md"
      - Tutorials:
        - MultiUser Implementation: "tutorials/multiuser-implementation.md"
        - FileSystem Implementation: "tutorials/filesystem-implementation.md"
        - Process Management Implementation: "tutorials/process-management-implementation.md"
        - XSM Instruction Cycle: "tutorials/xsm-instruction-cycle.md"
        - XSM Interrupts tutorial: "tutorials/xsm-interrupts-tutorial.md"
        - XSM Unprivileged tutorial: tutorials/xsm-unprivileged-tutorial.md
      - Support Tools:
        - Setting up: support-tools/setting-up.md
        - XFS Interface: support-tools/xfs-interface.md
        - SPL: support-tools/spl.md
        - ExpL: support-tools/expl.md
        - XSM Simulator: support-tools/xsm-simulator.md
      - Application Interface:
        - Application Binary Interface (ABI): abi.md
        - Low Level System Call Interface: os-design/sw-interface.md
        - High Level Library Interface: os-spec/dynamicmemoryroutines.md
        - Low Level Library Interface: abi.md
    - Others:
      - Test Programs: test-programs/index.md
  - Roadmap:
    - Roadmap: roadmap/index.md
    - Preparatory Stages:
      - Stage 1: roadmap/stage-01.md
      - Stage 2: roadmap/stage-02.md
      - Stage 3: roadmap/stage-03.md
      - Stage 4: roadmap/stage-04.md
      - Stage 5: roadmap/stage-05.md
      - Stage 6: roadmap/stage-06.md
      - Stage 7: roadmap/stage-07.md
      - Stage 8: roadmap/stage-08.md
      - Stage 9: roadmap/stage-09.md
      - Stage 10: roadmap/stage-10.md
      - Stage 11: roadmap/stage-11.md
      - Stage 12: roadmap/stage-12.md
    - Intermediate Stages:
      - Stage 13: roadmap/stage-13.md
      - Stage 14: roadmap/stage-14.md
      - Stage 15: roadmap/stage-15.md
      - Stage 16: roadmap/stage-16.md
      - Stage 17: roadmap/stage-17.md
      - Stage 18: roadmap/stage-18.md
      - Stage 19: roadmap/stage-19.md
    - Final Stages:
      - Stage 20: roadmap/stage-20.md
      - Stage 21: roadmap/stage-21.md
      - Stage 22: roadmap/stage-22.md
      - Stage 23: roadmap/stage-23.md
      - Stage 24: roadmap/stage-24.md
      - Stage 25: roadmap/stage-25.md
      - Stage 26: roadmap/stage-26.md
      - Stage 27: roadmap/stage-27.md
      - Stage 28: roadmap/stage-28.md
  - FAQ: faq.md
  - Student Feedback:
    - Student Feedback: feedback/index.md
    - NIT-C 2020: feedback/nitc20/index.md
    - NIT-C 2019: feedback/nitc19/index.md
    - IIT PKD 2018: feedback/iitpkd18/index.md
    - NIT-C 2018: feedback/nitc18/index.md
  - User Contributions: https://exposnitc.github.io/user-contrib/" target="_blank # can be moved later in this site itself
  - About:
    - About: about.md
    - Changelog: changelog.md
  - XOS: http://xosnitc.github.io" target="_blank # *hack* injected in the anchor code
