site_name: eXpOS NITC
site_url: https://anandubajith.github.io/expos-v2/
site_description: >-
  OS Lab website for NIT Calicut

# Copyright
copyright: >-
  National Insititute of Technology, Calicut <br/>
  <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">
    <img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/80x15.png" />
  </a>

extra_css:
  - assets/css/extra.css
# repo_url: https://github.com/eXpOSNitc/eXpOSNitc.github.io
# repo_name: eXpOSNitc/eXpOSNitc.github.io
# Configuration
theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/logo.png
  custom_dir: overrides
  theme:
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/exposnitc
    - icon: fontawesome/brands/google
      link: https://groups.google.com/g/xos-users

# Extensions
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Page tree
nav:
  - Home: index.md
  - Documentation:
    - Documentation: documentation.md
    - Operating System:
      - Specification:
        - Specification: os-spec/index.md
        - Overview: os-spec/overview.md
        - eXpOS Abstractions: os-spec/expos-abstractions.md
        - The Logical File System eXpFS: os-spec/expfs.md
        - Process Model: os-spec/processmodel.md
        - Synchronization and Access Control: os-spec/synchronization.md
        - Micellaneous: os-spec/misc.md
        - Multi-User Extension to eXpOS: os-spec/multiuser.md
        - Application Programmer's Interface (API):
          - High Level System Call Interface: os-spec/systemcallinterface.md
          - High Level Library Interface: os-spec/dynamicmemoryroutines.md
        - eXpOS Shell Specification: os-spec/shell-spec.md
      - Design: 
        - Design: os-design/index.md
        - Micellaneous: os-design/misc.md
        - Exception Handler: os-design/exe-handler.md
        - Timer: os-design/timer.md
        - Disk Interrupt Handler: os-design/disk-interrupt.md
        - Terminal Interrupt Handler: os-design/term-handler.md
        - Shutdown: os-design/shutdown.md
        - Create: os-design/create.md
        - Delete: os-design/delete.md
        - Open: os-design/open.md
        - Close: os-design/close.md
        - Read: os-design/read.md
        - Write: os-design/write.md
        - Seek: os-design/seek.md
        - Fork: os-design/fork.md
        - Exec: os-design/exec.md
        - Exit: os-design/exit.md
        - Process Micellaneous: os-design/proc-misc.md
        - Synchronization Algorithms: os-design/synchronization-algos.md
        - Semaphore Algorithms: os-design/semaphore-algos.md
        - Multi-User System Calls: os-design/multiusersyscalls.md
        - Disk Data Structures: os-design/disk-ds.md
        - Process Table: os-design/process-table.md
        - Memory Data Structures: os-design/mem-ds.md
        - Process State Diagram: os-design/state-diag.md
        - NeXpOS Design: os-design/nexpos.md
      - Implementation: 
        - Implementation: os-implementation.md
        - Kernel Stack Management:
          - During System Calls: os-design/stack-smcall.md
          - During Hardware interrupts or exceptions: os-design/stack-interrupt.md
          - During Module calls: os-design/stack-module.md
          - During Context Switch: os-design/timer-stack-management.md
    - Architecture:
      - Specification: 
        - XSM Architecture Specifcation: arch-spec/index.md
        - Virtual Machine Model: virtual-machine-spec.md
        - Machine Organisation: "arch-spec/machine-organization.md"
        - Interrupts and Exception Handling: arch-spec/interrupts-exception-handling.md
        - Instruction Set: arch-spec/instruction-set.md
        - Paging Hardware and Address Translation: arch-spec/paging-hardware.md
        - NEXSM (Two Core) Architecture Specification: arch-spec/nexsm.md
      - Modules:
        - Modules: "modules/index.md"
        - Module 0: "modules/module-00.md"
        - Module 1: "modules/module-01.md"
        - Module 2: "modules/module-02.md"
        - Module 3: "modules/module-03.md"
        - Module 4: "modules/module-04.md"
        - Module 5: "modules/module-05.md"
        - Module 6: "modules/module-06.md"
        - Module 7: "modules/module-07.md"
        - Module 8: "modules/module-08.md"
      - Tutorials:
        - MultiUser Implementation: "tutorials/multiuser-implementation.md"
        - FileSystem Implementation: "tutorials/filesystem-implementation.md"
        - Process Management Implementation: "tutorials/process-management-implementation.md"
        - XSM Instruction Cycle: "tutorials/xsm-instruction-cycle.md"
        - XSM Interrupts tutorial: "tutorials/xsm-interrupts-tutorial.md"
        - XSM Unprivileged tutorial: tutorials/xsm-unprivileged-tutorial.md
      - Support Tools:
        - Setting up: support-tools/setting-up.md
        - XFS Interface: support-tools/xfs-interface.md
        - SPL: support-tools/spl.md
        - ExpL: support-tools/expl.md
        - XSM Simulator: support-tools/xsm-simulator.md
        - Constants: support-tools/constants.md
      - Application Interface:
        - Application Binary Interface (ABI): abi.md
        - Low Level System Call Interface: os-design/sw-interface.md
        - High Level Library Interface: os-spec/dynamicmemoryroutines.md
        - Low Level Library Interface: abi.md
    - Others:
      - Test Programs: 
        - Test Programs: test-programs/index.md
        - Program 1: test-programs/test-program-01.md
        - Program 2: test-programs/test-program-02.md
        - Program 3: test-programs/test-program-03.md
        - Program 4: test-programs/test-program-04.md
        - Program 5: test-programs/test-program-05.md
        - Program 6: test-programs/test-program-06.md
        - Program 7: test-programs/test-program-07.md
        - Program 8: test-programs/test-program-08.md
        - Program 9: test-programs/test-program-09.md
        - Program 10: test-programs/test-program-10.md
        - Program 11: test-programs/test-program-11.md
        - Program 12: test-programs/test-program-12.md
        - Program 13: test-programs/test-program-13.md
        - Program 14: test-programs/test-program-14.md
        - Program 15: test-programs/test-program-15.md
        - Program 16: test-programs/test-program-16.md
  - Roadmap:
    - Roadmap: roadmap/index.md
    - Preparatory Stages:
      - Stage 1: roadmap/stage-01.md
      - Stage 2: roadmap/stage-02.md
      - Stage 3: roadmap/stage-03.md
      - Stage 4: roadmap/stage-04.md
      - Stage 5: roadmap/stage-05.md
      - Stage 6: roadmap/stage-06.md
      - Stage 7: roadmap/stage-07.md
      - Stage 8: roadmap/stage-08.md
      - Stage 9: roadmap/stage-09.md
      - Stage 10: roadmap/stage-10.md
      - Stage 11: roadmap/stage-11.md
      - Stage 12: roadmap/stage-12.md
    - Intermediate Stages:
      - Stage 13: roadmap/stage-13.md
      - Stage 14: roadmap/stage-14.md
      - Stage 15: roadmap/stage-15.md
      - Stage 16: roadmap/stage-16.md
      - Stage 17: roadmap/stage-17.md
      - Stage 18: roadmap/stage-18.md
      - Stage 19: roadmap/stage-19.md
    - Final Stages:
      - Stage 20: roadmap/stage-20.md
      - Stage 21: roadmap/stage-21.md
      - Stage 22: roadmap/stage-22.md
      - Stage 23: roadmap/stage-23.md
      - Stage 24: roadmap/stage-24.md
      - Stage 25: roadmap/stage-25.md
      - Stage 26: roadmap/stage-26.md
      - Stage 27: roadmap/stage-27.md
      - Stage 28: roadmap/stage-28.md
  - FAQ: faq.md
  - Student Feedback:
    - Student Feedback: feedback/index.md
    - NIT-C 2020: feedback/nitc20/index.md
    - NIT-C 2019: feedback/nitc19/index.md
    - IIT PKD 2018: feedback/iitpkd18/index.md
    - NIT-C 2018: feedback/nitc18/index.md
  - User Contributions: https://exposnitc.github.io/user-contrib/" target="_blank # can be moved later in this site itself
  - About:
    - About: about.md
    - Changelog: changelog.md
    - Project Reports: reports.md
  - XOS: http://xosnitc.github.io" target="_blank # hack injected in the anchor code