site_name: eXpOS NITC
site_url: https://example.com/
nav:
  - Home: index.md
  - About Us: about.md
  - Release Notes: releases.md
theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/logo.png
  theme:
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/exposnitc
    - icon: fontawesome/brands/google
      link: https://groups.google.com/g/xos-users
markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg